AllCops:
  DisplayCopNames: true
  CacheRootDirectory: tmp

# Configured cops
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/LineLength:
  Exclude:
    - 'resque-disable-job.gemspec'

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/resque-disable-job.rb'

Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatString:
  EnforcedStyle: percent
Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'

# Disabled cops

Lint/AssignmentInCondition:
  Enabled: false

Metrics:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericPredicate:
  Enabled: false