language: ruby

cache: bundler

branches:
  only: master

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
env:
  - COMMAND=rake
matrix:
  include:
    - rvm: 2.4
      env: COMMAND="rubocop -d"

services:
  - redis-server

script:
  - bundle exec rubocop -V
  - bundle exec $COMMAND
